#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-CDDB-File
Version  : 1.05
Release  : 1
URL      : https://cpan.metacpan.org/authors/id/T/TM/TMTM/CDDB-File-1.05.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/T/TM/TMTM/CDDB-File-1.05.tar.gz
Source1  : http://http.debian.net/debian/pool/main/libc/libcddb-file-perl/libcddb-file-perl_1.05-2.debian.tar.xz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0
Requires: perl-CDDB-File-license
Requires: perl-CDDB-File-man

%description
NAME
CDDB::File - Parse a CDDB/freedb data file
SYNOPSIS
my $disc = CDDB::File->new("rock/f4109511");

%package license
Summary: license components for the perl-CDDB-File package.
Group: Default

%description license
license components for the perl-CDDB-File package.


%package man
Summary: man components for the perl-CDDB-File package.
Group: Default

%description man
man components for the perl-CDDB-File package.


%prep
tar -xf %{SOURCE1}
cd ..
%setup -q -n CDDB-File-1.05
mkdir -p %{_topdir}/BUILD/CDDB-File-1.05/deblicense/
mv %{_topdir}/BUILD/debian/* %{_topdir}/BUILD/CDDB-File-1.05/deblicense/

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/perl-CDDB-File
cp deblicense/copyright %{buildroot}/usr/share/doc/perl-CDDB-File/deblicense_copyright
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot}
else
./Build install --installdirs=site --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)
/usr/lib/perl5/site_perl/5.26.1/CDDB/File.pm

%files license
%defattr(-,root,root,-)
/usr/share/doc/perl-CDDB-File/deblicense_copyright

%files man
%defattr(-,root,root,-)
/usr/share/man/man3/CDDB::File.3
